core/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register-agency/", views.RegisterAgencyView.as_view(), name="register_agency"),  # noqa
]

core/api/urls.py
from django.urls import path
from knox import views as knox_views
from . import views

app_name = "api"
urlpatterns = [
    path("", views.OverviewAPI.as_view(), name="overview"),
    path('sign-up/', views.SignUpAPI.as_view(), name="sign_up"),
    path('user-profile/', views.UserProfileAPI.as_view(), name="user_profile"),
]

# TRIPS ENDPOINTS
urlpatterns += [
    path('search-trips/', views.SearchTripsAPI.as_view(), name="search_trips"),  # noqa
    path('book-trip/', views.BookTripAPI.as_view(), name="book_trip"),
    path('user-bookings/', views.UserBookings.as_view(), name="user_bookings"),  # noqa
]


# PAYMENT ENDPOINTS
urlpatterns += [
    path('pay-for-trip/', views.PayForTripAPI.as_view(), name="pay_for_trip"),  # noqa
]


# SEATS ENDPOINTS
urlpatterns += [
    path('get-vehicle-seats/', views.VehicleSeatsAPI.as_view(), name="get_vehicle_seats"),  # noqa
]


# USER TICKETS ENDPOINTS
urlpatterns += [
    path('get-ticket/', views.GetTicketAPI.as_view(), name="get_ticket"),  # noqa
    path('user-tickets/', views.UserTicketsAPI.as_view(), name="user_tickets"),  # noqa
]


# LOCATIONS
urlpatterns += [
    path('locations/', views.AllLocationsAPI.as_view(), name="locations"),
]


# CATEGORIES
urlpatterns += [
    path('categories/', views.AllCategoriesAPI.as_view(), name="categories"),
]


# AGENCY ENDPOINTS
urlpatterns += [
    path('all-agencies/', views.GetAgenciesAPI.as_view(), name="agencies"),
]

# OTHER TRIP ENDPOINTS
urlpatterns += [
    path('all-trips/', views.AllTripsAPI.as_view(), name="all_trips"),
    path('trips-today/', views.TripsTodayAPI.as_view(), name="trips_today"),
]


# KNOX AUTHENTICATION
urlpatterns += [
    path('login/', views.LoginAPI.as_view(), name='login'),
    path('logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),  # noqa
]

core/backend/urls.py
from django.urls import path
from . import views

app_name = "backend"
urlpatterns = [
    path("", views.DashboardView.as_view(), name="backend"),
]

# VEHICLES
urlpatterns += [
    path("vehicles/", views.VehicleListView.as_view(), name="vehicles"),
    path("create-update-vehicle/", views.CreateUpdateVehicle.as_view(), name="create_update_vehicle"),  # noqa
    path("delete-vehicle/", views.DeleteVehicle.as_view(), name="delete_vehicle"),  # noqa
    path("free-vehicle-seats/",
         views.FreeVehicleSeatView.as_view(), name="free_vehicle_seats"),  # noqa
]

# TRANSACTIONS
urlpatterns += [
    path("transactions/", views.TransactionListView.as_view(), name="transactions"),
]

# BOOKINGS
urlpatterns += [
    path("bookings/", views.BookingListView.as_view(), name="bookings"),
]

# TICKETS
urlpatterns += [
    path("tickets/", views.TicketListView.as_view(), name="tickets"),
]

# SEATS
urlpatterns += [
    path("seats/", views.SeatListView.as_view(), name="seats"),
    path("create-update-seat/", views.CreateUpdateSeat.as_view(), name="create_update_seat"),  # noqa
    path("delete-seat/", views.DeleteSeat.as_view(), name="delete_seat"),  # noqa
]

# TRIPS
urlpatterns += [
    path("trips/", views.TripListView.as_view(), name="trips"),
    path("create-update-trip/", views.CreateUpdateTrip.as_view(), name="create_update_trip"),  # noqa
    path("delete-trip/", views.DeleteTrip.as_view(), name="delete_trip"),  # noqa
]

# CATEGORIES
urlpatterns += [
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path("create-update-category/", views.CreateUpdateCategory.as_view(), name="create_update_category"),  # noqa
    path("delete-category/", views.DeleteCategory.as_view(), name="delete_category"),  # noqa
]

# AGENCIES
urlpatterns += [
    path("agencies/", views.AgencyListView.as_view(), name="agencies"),
    path("create-update-agency/", views.CreateUpdateAgency.as_view(), name="create_update_agency"),  # noqa
    path("delete-agency/", views.DeleteAgency.as_view(), name="delete_agency"),  # noqa
    path('agency-details/', views.ApproveDisapproveAgencyView.as_view(),
         name="approve_disapprove_agency"),
]

# USERS
urlpatterns += [
    path("users/", views.UserListView.as_view(), name="users"),
]


# WALLETS
urlpatterns += [
    path("wallets/", views.WalletListView.as_view(), name="wallets"),
    path("cashout/", views.CashoutView.as_view(), name="cashout"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('backend/', include('backend.urls')),
    path('', include('accounts.urls')),
]


urlpatterns += [
    path('api-auth/', include('rest_framework.urls'))
]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/backend/models.py
import decimal
import time
import string
import random
import uuid
from django.db import models

# from accounts.models import User


class Agency(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    website = models.CharField(max_length=255, null=True, blank=True)
    wallet = models.ForeignKey('Wallet', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    business_certificate = models.ImageField(upload_to="agency_certificate/", null=True, blank=True)  # noqa
    contact_person_ID = models.ImageField(upload_to="user_ID/", null=True, blank=True)  # noqa
    is_approved = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name if self.name else "agency"

    class Meta:
        db_table = 'agency'


class Vehicle(models.Model):
    name = models.CharField(max_length=255)
    vin = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey('VehicleCategory', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name if self.name else "vehicle"

    class Meta:
        db_table = 'vehicle'


class Seat(models.Model):
    seat_num = models.IntegerField(default=0)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    is_booked = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.seat_num) if str(self.seat_num) else "seat"

    class Meta:
        db_table = 'seat'


class VehicleCategory(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_agencies_in_category(self):
        vehicles = Vehicle.objects.filter(category=self)
        agencies = Agency.objects.none()
        for vehicle in vehicles:
            agencies |= Agency.objects.filter(id=vehicle.agency.id)
        return agencies

    def __str__(self):
        return self.name if self.name else "category"

    class Meta:
        db_table = 'category'


class Trip(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    source = models.CharField(max_length=255, null=True, blank=True)
    destination = models.CharField(max_length=255, null=True, blank=True)
    price = models.DecimalField(decimal_places=3, max_digits=10, default=0)
    date = models.DateField(null=True, blank=True)
    time = models.TimeField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_trip_type(self):
        return self.vehicle.category.name if self.vehicle else None

    def __str__(self):
        return self.source + "-" + self.destination if self.source and self.destination else "trip"  # noqa

    class Meta:
        db_table = 'trip'


class Booking(models.Model):
    def generate_ticket_id():
        time_id = str(int(time.time() * 1000))
        return "G".join(random.choices(string.ascii_uppercase + time_id + string.digits, k=6))
    booking_code = models.CharField(max_length=255, default=generate_ticket_id)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    seats = models.ManyToManyField(Seat, blank=True)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    date = models.DateTimeField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_seat_numbers(self):
        data = self.seats.all()
        seats = ""
        for seat in data:
            seats += str(seat.seat_num) + ", "
        return seats.strip(", ")

    def __str__(self):
        return self.user.email if self.user.email else "booking"

    class Meta:
        db_table = 'booking'


class Ticket(models.Model):
    def generate_ticket_id():
        time_id = str(int(time.time() * 1000))
        return "".join(random.choices(string.ascii_uppercase + time_id + string.digits, k=12))
    ticket_id = models.CharField(max_length=100, default=generate_ticket_id)
    transaction = models.ForeignKey('Transaction', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.ticket_id if self.ticket_id else "ticket"

    class Meta:
        db_table = 'ticket'


class Transaction(models.Model):
    def generate_transaction_id():
        time_id = str(int(time.time() * 100))
        return "".join(random.choices(string.ascii_uppercase + time_id + string.digits, k=12))
    transaction_id = models.CharField(max_length=255, primary_key=True, default=generate_transaction_id)  # noqa
    external_id = models.CharField(max_length=255, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    network = models.CharField(max_length=255, null=True, blank=True)
    status_code = models.CharField(max_length=255, null=True, blank=True)
    status_message = models.CharField(max_length=255, null=True, blank=True)
    source_phone = models.CharField(max_length=255, null=True, blank=True)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    note = models.CharField(max_length=255, null=True, blank=True)
    transaction_type = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id if self.transaction_id else "transaction"


class Wallet(models.Model):
    wallet_id = models.CharField(max_length=100, default=uuid.uuid4)
    main_balance = models.DecimalField(decimal_places=2, max_digits=10, default=0.0)  # noqa
    available_balance = models.DecimalField(decimal_places=2, max_digits=50, default=0.0)  # noqa
    date_added = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def credit_available_balance(self, amount):
        self.available_balance += decimal.Decimal(amount)
        self.save()

    def debit_available_balance(self, amount):
        self.available_balance -= decimal.Decimal(amount)
        self.save()

    def credit_main_balance(self, amount):
        self.main_balance += decimal.Decimal(amount)
        self.save()

    def debit_main_balance(self, amount):
        self.main_balance -= decimal.Decimal(amount)
        self.save()

    def credit_wallet(self, amount):
        self.main_balance += decimal.Decimal(amount)
        self.available_balance += decimal.Decimal(amount)
        self.save()

    def debit_wallet(self, amount):
        self.main_balance -= decimal.Decimal(amount)
        self.available_balance -= decimal.Decimal(amount)
        self.save()

    def get_wallet_balance(self):
        return decimal.Decimal(self.main_balance)

    def __str__(self):
        return self.wallet_id

    class Meta:
        permissions = [
            ("cashout_from_wallet", "Can cashout from wallet"),
        ]

core/backend/views/booking.py
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from backend.models import Booking

from core.utils.decorators import MustLogin


class BookingListView(View):
    permission_required = [
        "backend.view_booking",
    ]
    template = "backend/lists/bookings.html"

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        if request.user.is_staff or request.user.is_superuser:
            bookings = Booking.objects.all().order_by('-id')
        elif request.user.is_agency_admin:
            bookings = Booking.objects.filter(
                trip__vehicle__agency=request.user.agency)
        context = {'bookings': bookings}
        return render(request, self.template, context)

core/backend/views/category.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.utils.html import strip_tags

from backend.models import VehicleCategory
from backend.forms import VehicleCategoryForm
from core.utils.decorators import MustLogin


class CategoryListView(PermissionRequiredMixin, View):
    permission_required = [
        "backend.view_vehiclecategory",
    ]
    template = "backend/lists/categories.html"

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        categories = VehicleCategory.objects.all().order_by('-id')
        context = {'categories': categories}
        return render(request, self.template, context)


class CreateUpdateCategory(PermissionRequiredMixin, View):
    permission_required = [
        "backend.add_vehiclecategory",
        "backend.change_vehiclecategory",
    ]
    template = "backend/create_update_category.html"

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        category_id = request.GET.get('category_id')
        category = VehicleCategory.objects.filter(id=category_id).first()
        context = {"category": category}  # noqa
        return render(request, self.template, context)

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        category_id = request.POST.get('category_id')

        if category_id:
            # category exists
            category = VehicleCategory.objects.filter(id=category_id).first()
            form = VehicleCategoryForm(request.POST, request.FILES, instance=category)  # noqa
            if form.is_valid():
                category = form.save(commit=False)
                category.save()
                messages.success(request, 'Vehicle Category Details Updated Successfully.')  # noqa
                return redirect('backend:categories')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        else:
            # it's a new category
            form = VehicleCategoryForm(request.POST, request.FILES)
            if form.is_valid():
                category = form.save(commit=False)
                category.save()
                messages.success(request, 'New Vehicle Category Created Successfully.')  # noqa
                return redirect('backend:categories')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteCategory(PermissionRequiredMixin, View):
    permission_required = [
        "backend.delete_vehiclecategory",
    ]

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('backend:categories')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        category_id = request.POST.get('category_id')
        category = VehicleCategory.objects.filter(id=category_id).first()
        category.delete()
        messages.success(request, 'Vehicle Category Deleted Successfully.')
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

core/backend/templates/backend/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    {% load humanize %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="RideMate">
    <meta name="author" content="RideMate">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/logos/logo.png' %}" type="image/png">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">

    <!-- extra css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{% block page_title %}{% endblock %} | RideMate Booking Backend</title>

</head>

<body>
    <div id="main-overlay"></div>
    <!-- Sidebar -->
    <aside id="side-bar" style="background : white" data-active="{% block active_item %}dashboard{% endblock %}">
        <div class="header" style="background-color : white">
            <img src="{% static 'images/logos/dasboard14.png' %}" style="height: 50px; width:auto;" alt="">
        </div>

        <h6 class="item-header mt-3"><font color = "black">STATISTICS</font></h6>
        <div class="side-bar-item" title="Dashboard" id="dashboard">
            <a href="{% url 'backend:backend' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi bi-bank2" style="font-size: 1.5em;",></i></font>
                </div>
                <div class="lable">
                    <font color = "black"><span>Dashboard</span></font>
                </div>
            </a>
        </div>
        <h6 class="item-header mt-3"><font color = "black">CONFIGURATIONS</font></h6>
        <div class="side-bar-item" title="agencies" id="agencies">
            <a href="{% url 'backend:agencies' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-menu-button" style="font-size: 1.5em;" ></i></font>
                    {% comment %} <i class="bi bi-bag" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Agencies</span></font>
                </div>
            </a>
        </div>
        <div class="side-bar-item" title="vehicles" id="vehicles">
            <a href="{% url 'backend:vehicles' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi bi-bag" style="font-size: 1.5em;"></i></font>
                </div>
                <div class="lable">
                    <font color = "black"><span>Vehicles</span></font>
                </div>
            </a>
        </div>
        <div class="side-bar-item" title="seats" id="seats">
            <a href="{% url 'backend:seats' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-journal-plus" style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi bi-check-square" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Seats</span></font>
                </div>
            </a>
        </div>
        {% if perms.backend.view_vehiclecategory %}
        <div class="side-bar-item" title="category" id="category">
            <a href="{% url 'backend:categories' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-hdd-stack" style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi bi-check-square" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Category</span></font>
                </div>
            </a>
        </div>
        {% endif %}
        <div class="side-bar-item" title="trips" id="trips">
            <a href="{% url 'backend:trips' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-calendar-week" style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi bi-check-square" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Trips</span></font>
                </div>
            </a>
        </div>

        <h6 class="item-header mt-3"> <font color = "black">OBJECTS</font></h6>
        <div class="side-bar-item" title="Bookings" id="bookings">
            <a href="{% url 'backend:bookings' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-journals" style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi bi-collection" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Bookings</span></font>
                </div>
            </a>
        </div>

        <div class="side-bar-item" title="Tickers" id="banners">
            <a href="{% url 'backend:tickets' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bx bx-chalkboard" style="font-size: 1.5em;"></i></font>
                </div>
                <div class="lable">
                    <font color = "black"><span>Tickets</span></font>
                </div>
            </a>
        </div>

        <div class="side-bar-item" title="Transactions" id="transactions">
            <a href="{% url 'backend:transactions' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-book-half"  style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi bi-people" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Transactions</span></font>
                </div>
            </a>
        </div>
        <h6 class="item-header mt-3"> <font color = "black">ACCOUNTS</font></h6>
        <div class="side-bar-item" title="Wallets" id="wallets">
            <a href="{% url 'backend:wallets' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-wallet" style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi-wallets" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Wallets</span></font>
                </div>
            </a>
        </div>
        <div class="side-bar-item" title="Transactions" id="transactions">
            <a href="{% url 'backend:users' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-people" style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi-wallets2" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Users</span></font>
                </div>
            </a>
        </div>
        <h6 class="item-header mt-3"> <font color = "black">LOGOUT</font></h6>
        <div class="side-bar-item" title="Logout" id="logout">
            <a href="{% url 'accounts:logout' %}" class="d-flex">
                <div class="icon">
                    <font color = "black"><i class="bi-box-arrow-left" style="font-size: 1.5em;"></i></font>
                    {% comment %} <i class="bi bi-lock" style="font-size: 1.5em;"></i> {% endcomment %}
                </div>
                <div class="lable">
                    <font color = "black"><span>Logout</span></font>
                </div>
            </a>
        </div>
    </aside>
    <!-- End Sidebar -->

    <main id="main-page">
        <nav id="main-nav">
            <div class="nav-left">
                <div class="nav-item">
                    <button id="toggle-side-bar" class="btn-white"><i class="bi bi-list"
                            style="font-size: 2rem;"></i></button>
                </div>
            </div>
            <div class="nav-right">
                <div class="nav-item">
                    <div class="dropdown">
                        <div class="rounded-profile-picture">
                            <img src="{% static 'images/user_icon.png' %}" alt="User profile picture">
                        </div>
                        <h6 class="text m-1">{{request.user.email|lower}}</h6>
                        <button class="btn-white dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" data-target=".content" aria-haspopup="true"
                            aria-expanded="false"></button>
                        <div class="content overlay-toggle">
                            <div class="my-3">
                                <p class="p-0 m-0 text text-center">{{request.user.email|lower}}</p>
                                <p class="p-0 m-0 text text-center text-muted">{{request.user.agency.name}}</p>
                            </div>
                            <a class="drop-item"><i class="bi bi-person"></i> Profile</a>
                            <a href="{% url 'accounts:logout' %}" class="drop-item"><i class="bi bi-lock"></i>
                                Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <div class="main-content">
            {% if messages %}
            {% for message in messages %}

            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                <p class="p-0 m-0 text text-center col-md-6 mx-auto">{{message}}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>

        <section class="footer" style="background-color:#B9B9BA ;">
            © Copyright <a href="#" class="text text-primary"><font color = "black">RideMate Transport Services</font></a>. All Rights Reserved
        </section>
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

core/backend/templates/backend/create_update_agency.html
{% extends 'backend/base.html' %}
{% block active_item %}agencies{% endblock %}
{% block page_title %}Agencies{% endblock %}


{% block content %}
<div class="breadcrumb">
    <a href="{% url 'backend:backend' %}">Dashboard</a>
    <a class="active"><i class="bi bi-chevron-right"></i> Agencies</a>
</div>
<div class="row col-md-11 mx-auto">
    <section class="card col-md-9 mx-auto p-3">
        <div class="d-flex justify-content-between">
            <h6>CREATE/UPDATE AGENCY</h6>
        </div>
        {% include 'backend/forms/form_agency.html' %}
    </section>
</div>
{% endblock %}