core/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register-agency/", views.RegisterAgencyView.as_view(), name="register_agency"),  # noqa
]

core/api/urls.py
from django.urls import path
from knox import views as knox_views
from . import views

app_name = "api"
urlpatterns = [
    path("", views.OverviewAPI.as_view(), name="overview"),
    path('sign-up/', views.SignUpAPI.as_view(), name="sign_up"),
    path('user-profile/', views.UserProfileAPI.as_view(), name="user_profile"),
]

# TRIPS ENDPOINTS
urlpatterns += [
    path('search-trips/', views.SearchTripsAPI.as_view(), name="search_trips"),  # noqa
    path('book-trip/', views.BookTripAPI.as_view(), name="book_trip"),
    path('user-bookings/', views.UserBookings.as_view(), name="user_bookings"),  # noqa
]


# PAYMENT ENDPOINTS
urlpatterns += [
    path('pay-for-trip/', views.PayForTripAPI.as_view(), name="pay_for_trip"),  # noqa
]


# SEATS ENDPOINTS
urlpatterns += [
    path('get-vehicle-seats/', views.VehicleSeatsAPI.as_view(), name="get_vehicle_seats"),  # noqa
]


# USER TICKETS ENDPOINTS
urlpatterns += [
    path('get-ticket/', views.GetTicketAPI.as_view(), name="get_ticket"),  # noqa
    path('user-tickets/', views.UserTicketsAPI.as_view(), name="user_tickets"),  # noqa
]


# LOCATIONS
urlpatterns += [
    path('locations/', views.AllLocationsAPI.as_view(), name="locations"),
]


# CATEGORIES
urlpatterns += [
    path('categories/', views.AllCategoriesAPI.as_view(), name="categories"),
]


# AGENCY ENDPOINTS
urlpatterns += [
    path('all-agencies/', views.GetAgenciesAPI.as_view(), name="agencies"),
]

# OTHER TRIP ENDPOINTS
urlpatterns += [
    path('all-trips/', views.AllTripsAPI.as_view(), name="all_trips"),
    path('trips-today/', views.TripsTodayAPI.as_view(), name="trips_today"),
]


# KNOX AUTHENTICATION
urlpatterns += [
    path('login/', views.LoginAPI.as_view(), name='login'),
    path('logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),  # noqa
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('backend/', include('backend.urls')),
    path('', include('accounts.urls')),
]


urlpatterns += [
    path('api-auth/', include('rest_framework.urls'))
]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from accounts.manager import AccountManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_agency_admin = models.BooleanField(default=False)
    agency = models.ForeignKey('backend.Agency', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    date_joined = models.DateTimeField(auto_now_add=True)

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name if self.first_name or self.last_name else 'N/A'  # noqa

    objects = AccountManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email if self.email else "user"

    class Meta:
        db_table = 'user'

core/accounts/views.py
from http.client import HTTPResponse
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, Permission
import datetime


from backend.forms import AgencyForm
from accounts.manager import AccountManager
from .models import User


class RegisterAgencyView(View):
    template = "accounts/register.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template, {})

    def post(self, request, *args, **kwargs):
        form = AgencyForm(request.POST, request.FILES or None)
        user_email = request.POST.get("user_email")
        user_password = request.POST.get("password")
        first_name = request.POST.get("firstname")
        last_name = request.POST.get("lastname")
        if form.is_valid():
            agency = form.save()
            if agency:
                # agency is created so go ahead and create an admin use for agency
                user = User.objects.create_agency_admin(
                    email=user_email,
                    password=user_password,
                )
                if user:
                    # user is created so go ahead and assign agency to user
                    user.agency = agency
                    user.first_name = first_name
                    user.last_name = last_name
                    # assign group to user
                    group, created = Group.objects.get_or_create(name="Agency")
                    user.groups.add(group)
                    user.save()
                    # login user after a successful registration
                    # user = authenticate(
                    #     email=user_email,
                    #     password=user_password,
                    # )
                    # if user:
                    #     login(request, user)
                    #     messages.success(
                    #         request, f"Hello {user.first_name}, Welcome to Ridemate")
                    #     return redirect("backend:backend")
                    # else:
                    #     return HTTPResponse("Something went wrong! Contact admins.")
                    messages.info(request, "Request Submitted Successfully. Your details are under review. You will be contacted soon.")
                    return redirect("accounts:login")
        messages.success(request, "Agency Not Created Contact Admins!")
        return redirect("accounts:login")


class LoginView(View):
    template = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template, context)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            user.last_login = datetime.datetime.now()
            messages.success(request, 'Hi there, Welcome {}'.format(user.first_name))
            return redirect('backend:backend')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('accounts:login')


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, 'You have been logged out')
        return redirect('accounts:login')

core/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="Description" content="">
    <meta name="Author" content="">
    <meta name="Keywords" content="" />

    <!-- Title -->
    <title> RideMate | {% block pagetitle %} {% endblock %}</title>

    <!-- django static files -->
    {% load static %}

    <!--- Favicon --->
    <link rel="icon" href="{% static 'images/logos/logo.png' %}" type="image/x-icon" />


    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body class="error-page1 main-body">

    <!-- Page -->
    <div class="page">

        <div class="container-fluid">
            <div class="row no-gutter py-5">
                <!-- The content half -->
                <div class="col-md-6 col-lg-6 col-xl-5 bg-white mx-auto">
                    <div class="login d-flex align-items-center">
                        <!-- Demo content-->
                        <div class="container p-0 py-5">
                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-xl-10 mx-auto">
                                    <div class="card shadow container-fluid">
                                        <div class="mb-3 d-flex mt-2 mx-auto">
                                            <a href=""><img src=" {% static 'images/logos/logo.png' %}"
                                                    class="sign-favicon-a ht-30" alt="logo"
                                                    style="height: 100px; margin-top: 5px; width: auto; border-radius: 50%;">
                                            </a>
                                        </div>

                                        <!-- NOTE: BLOCK CONTENT GOES HERE -->
                                        {% block content %}

                                        {% endblock %}
                                    </div>
                                </div>
                            </div>
                        </div><!-- End -->
                    </div>
                </div><!-- End -->
            </div>
        </div>

    </div>
    <!-- End Page -->

    <!--- Custom js --->
    <script src="{% static 'assets/js/custom.js' %}"></script>

</body>

</html>

core/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block pagetitle %} Login {% endblock %}
{% load static %}
{% block content %}
<div class="card-body" style="width: 80%;">
    <div class="main-signup-header">
        <!-- handle alert messages -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        <h2 class="text-primary text-center" style="color:black;">Login</h2>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email</label>
                <input class="form-control" id="email" name="email" placeholder="Enter Email" type="email" required>
            </div>
            <div class="form-group mb-2">
                <label for="password">Password</label>
                <input class="form-control" id="password" name="password" placeholder="Enter your password"
                    type="password" required>
            </div>
            <button class="btn btn-sm btn-primary" type="submit">Login</button>

        </form>
        <div class="main-signin-footer mt-5">
            <p>New to RideMate? <a href="{% url 'accounts:register_agency' %}">Sign-up</a> as a travel agency</p>
        </div>
    </div>
</div>
<!-- NOTE ENDS -->
{% endblock %}

core/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block pagetitle %} Register Agency {% endblock %}
{% load static %}
{% block content %}
<!-- NOTE STARTS -->
<div class="card-sigin mt-2">
    <div class="main-signup-header mx-auto">
        <!-- message -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}

        <h5 class="fw-semibold mb-4 text-primary text-center">Sign-up your agency with us!</h5>
        <form action="{% url 'accounts:register_agency' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="name">Agency Name</label>
                <input class="form-control" id="name" name="name" placeholder="Enter agency name" type="text" required>
            </div>

            <div class="form-group mb-3">
                <label for="phone">Agency Phone</label>
                <input class="form-control" id="phone" name="phone" placeholder="Enter agency phone" type="text"
                    required>
            </div>
            <div class="form-group mb-3">
                <label for="email">Agency Email</label>
                <input class="form-control" id="email" name="email" placeholder="Enter agency email" type="email"
                    required>
            </div>
            <div class="form-group mb-3">
                <label for="address">Agency Address</label>
                <input class="form-control" id="address" name="address" placeholder="Enter agency address" type="text"
                    required>
            </div>
            <div class="form-group mb-3">
                <label for="website">Agency Website</label>
                <input class="form-control" id="website" name="website" placeholder="Enter agency website" type="text"
                    required>
            </div>
            <div class="form-group mt-3">
                <label for="business_certificate">Business Certificate <span class="text text-danger">*</span> <span
                        class="text-primary">Upload picture of business certificate for verification</span> </label>
                {% if agency.business_certificate %}
                <span>Current File: </span>
                <img src="{{agency.business_certificate.file}}" alt="">
                {% endif %}
                <input class="form-control" type="file" accept="image/*" name="business_certificate" required>
                <div class="invalid-feedback">
                    Please this field is required.
                </div>
            </div>
            <div class="form-group mt-3">
                <label for="contact_person_ID">Agency Admin's ID <span class="text text-danger">*</span> <span
                        class="text-primary">Upload picture of Ghana card</span> </label> <br>
                {% if agency.contact_person_ID %}
                <span>Current File: </span>
                <img src="{{agency.contact_person_ID.file}}" alt="">
                {% endif %}
                <input class="form-control" type="file" accept="image/*" name="contact_person_ID" required>
                <div class="invalid-feedback">
                    Please this field is required.
                </div>
            </div>
            <br>
            <hr>
            <center>
                <b class="text-center text-primary">Who will manage the agency?</b>
            </center>
            <hr>
            <br>
            <!-- FOR CREATED AGENCY ADMIN -->
            <div class="form-group mb-3">
                <label for="firstname">Firstname</label>
                <input class="form-control" id="firstname" name="firstname" placeholder="Enter your firstname"
                    type="text" required>
            </div>
            <div class="form-group mb-3">
                <label for="lastname">Lastname</label>
                <input class="form-control" id="lastname" name="lastname" placeholder="Enter your lastname" type="text"
                    required>
            </div>
            <div class="form-group mb-3">
                <label for="user_email">Email</label> <small class="text-primary">This is what you will login
                    with</small>
                <input class="form-control" id="user_email" name="user_email" placeholder="Enter your personal email"
                    type="email" required>
            </div>
            <div class="form-group mb-3">
                <label for="password">Password</label>
                <input class="form-control" id="password" name="password" placeholder="Enter your password"
                    type="password" required>
            </div>
            <div class="form-group mb-3">
                <label for="confirm-password">Confirm Password</label>
                <input class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm Password"
                    type="password">
            </div>
            <button class="btn btn-sm btn-primary btn-block" onclick="matchPassword()" type="submit">Sign Up</button>

        </form>
        <div class="main-signin-footer mt-5">
            <p>Already have an account? <a href="{% url 'accounts:login' %}">Login</a></p>
        </div>
    </div>
</div>
<!--  ENDS -->


<script>
    // confirm password and password confirmation
    const matchPassword = () => {
        const password = document.getElementById('password').value;
        const confirmPassword = document.getElementById('confirm_password').value;
        if (password !== confirmPassword) {
            document.getElementById('confirm_password').setCustomValidity('Passwords do not match.');
        }
    }
</script>


{% endblock %}