core/api/urls.py
from django.urls import path
from knox import views as knox_views
from . import views

app_name = "api"
urlpatterns = [
    path("", views.OverviewAPI.as_view(), name="overview"),
    path('sign-up/', views.SignUpAPI.as_view(), name="sign_up"),
    path('user-profile/', views.UserProfileAPI.as_view(), name="user_profile"),
]

# TRIPS ENDPOINTS
urlpatterns += [
    path('search-trips/', views.SearchTripsAPI.as_view(), name="search_trips"),  # noqa
    path('book-trip/', views.BookTripAPI.as_view(), name="book_trip"),
    path('user-bookings/', views.UserBookings.as_view(), name="user_bookings"),  # noqa
]


# PAYMENT ENDPOINTS
urlpatterns += [
    path('pay-for-trip/', views.PayForTripAPI.as_view(), name="pay_for_trip"),  # noqa
]


# SEATS ENDPOINTS
urlpatterns += [
    path('get-vehicle-seats/', views.VehicleSeatsAPI.as_view(), name="get_vehicle_seats"),  # noqa
]


# USER TICKETS ENDPOINTS
urlpatterns += [
    path('get-ticket/', views.GetTicketAPI.as_view(), name="get_ticket"),  # noqa
    path('user-tickets/', views.UserTicketsAPI.as_view(), name="user_tickets"),  # noqa
]


# LOCATIONS
urlpatterns += [
    path('locations/', views.AllLocationsAPI.as_view(), name="locations"),
]


# CATEGORIES
urlpatterns += [
    path('categories/', views.AllCategoriesAPI.as_view(), name="categories"),
]


# AGENCY ENDPOINTS
urlpatterns += [
    path('all-agencies/', views.GetAgenciesAPI.as_view(), name="agencies"),
]

# OTHER TRIP ENDPOINTS
urlpatterns += [
    path('all-trips/', views.AllTripsAPI.as_view(), name="all_trips"),
    path('trips-today/', views.TripsTodayAPI.as_view(), name="trips_today"),
]


# KNOX AUTHENTICATION
urlpatterns += [
    path('login/', views.LoginAPI.as_view(), name='login'),
    path('logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),  # noqa
]

core/backend/urls.py
from django.urls import path
from . import views

app_name = "backend"
urlpatterns = [
    path("", views.DashboardView.as_view(), name="backend"),
]

# VEHICLES
urlpatterns += [
    path("vehicles/", views.VehicleListView.as_view(), name="vehicles"),
    path("create-update-vehicle/", views.CreateUpdateVehicle.as_view(), name="create_update_vehicle"),  # noqa
    path("delete-vehicle/", views.DeleteVehicle.as_view(), name="delete_vehicle"),  # noqa
    path("free-vehicle-seats/",
         views.FreeVehicleSeatView.as_view(), name="free_vehicle_seats"),  # noqa
]

# TRANSACTIONS
urlpatterns += [
    path("transactions/", views.TransactionListView.as_view(), name="transactions"),
]

# BOOKINGS
urlpatterns += [
    path("bookings/", views.BookingListView.as_view(), name="bookings"),
]

# TICKETS
urlpatterns += [
    path("tickets/", views.TicketListView.as_view(), name="tickets"),
]

# SEATS
urlpatterns += [
    path("seats/", views.SeatListView.as_view(), name="seats"),
    path("create-update-seat/", views.CreateUpdateSeat.as_view(), name="create_update_seat"),  # noqa
    path("delete-seat/", views.DeleteSeat.as_view(), name="delete_seat"),  # noqa
]

# TRIPS
urlpatterns += [
    path("trips/", views.TripListView.as_view(), name="trips"),
    path("create-update-trip/", views.CreateUpdateTrip.as_view(), name="create_update_trip"),  # noqa
    path("delete-trip/", views.DeleteTrip.as_view(), name="delete_trip"),  # noqa
]

# CATEGORIES
urlpatterns += [
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path("create-update-category/", views.CreateUpdateCategory.as_view(), name="create_update_category"),  # noqa
    path("delete-category/", views.DeleteCategory.as_view(), name="delete_category"),  # noqa
]

# AGENCIES
urlpatterns += [
    path("agencies/", views.AgencyListView.as_view(), name="agencies"),
    path("create-update-agency/", views.CreateUpdateAgency.as_view(), name="create_update_agency"),  # noqa
    path("delete-agency/", views.DeleteAgency.as_view(), name="delete_agency"),  # noqa
    path('agency-details/', views.ApproveDisapproveAgencyView.as_view(),
         name="approve_disapprove_agency"),
]

# USERS
urlpatterns += [
    path("users/", views.UserListView.as_view(), name="users"),
]


# WALLETS
urlpatterns += [
    path("wallets/", views.WalletListView.as_view(), name="wallets"),
    path("cashout/", views.CashoutView.as_view(), name="cashout"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('backend/', include('backend.urls')),
    path('', include('accounts.urls')),
]


urlpatterns += [
    path('api-auth/', include('rest_framework.urls'))
]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/backend/models.py
import decimal
import time
import string
import random
import uuid
from django.db import models

# from accounts.models import User


class Agency(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    website = models.CharField(max_length=255, null=True, blank=True)
    wallet = models.ForeignKey('Wallet', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    business_certificate = models.ImageField(upload_to="agency_certificate/", null=True, blank=True)  # noqa
    contact_person_ID = models.ImageField(upload_to="user_ID/", null=True, blank=True)  # noqa
    is_approved = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name if self.name else "agency"

    class Meta:
        db_table = 'agency'


class Vehicle(models.Model):
    name = models.CharField(max_length=255)
    vin = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey('VehicleCategory', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name if self.name else "vehicle"

    class Meta:
        db_table = 'vehicle'


class Seat(models.Model):
    seat_num = models.IntegerField(default=0)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    is_booked = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.seat_num) if str(self.seat_num) else "seat"

    class Meta:
        db_table = 'seat'


class VehicleCategory(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_agencies_in_category(self):
        vehicles = Vehicle.objects.filter(category=self)
        agencies = Agency.objects.none()
        for vehicle in vehicles:
            agencies |= Agency.objects.filter(id=vehicle.agency.id)
        return agencies

    def __str__(self):
        return self.name if self.name else "category"

    class Meta:
        db_table = 'category'


class Trip(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    source = models.CharField(max_length=255, null=True, blank=True)
    destination = models.CharField(max_length=255, null=True, blank=True)
    price = models.DecimalField(decimal_places=3, max_digits=10, default=0)
    date = models.DateField(null=True, blank=True)
    time = models.TimeField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_trip_type(self):
        return self.vehicle.category.name if self.vehicle else None

    def __str__(self):
        return self.source + "-" + self.destination if self.source and self.destination else "trip"  # noqa

    class Meta:
        db_table = 'trip'


class Booking(models.Model):
    def generate_ticket_id():
        time_id = str(int(time.time() * 1000))
        return "G".join(random.choices(string.ascii_uppercase + time_id + string.digits, k=6))
    booking_code = models.CharField(max_length=255, default=generate_ticket_id)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    seats = models.ManyToManyField(Seat, blank=True)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    date = models.DateTimeField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def get_seat_numbers(self):
        data = self.seats.all()
        seats = ""
        for seat in data:
            seats += str(seat.seat_num) + ", "
        return seats.strip(", ")

    def __str__(self):
        return self.user.email if self.user.email else "booking"

    class Meta:
        db_table = 'booking'


class Ticket(models.Model):
    def generate_ticket_id():
        time_id = str(int(time.time() * 1000))
        return "".join(random.choices(string.ascii_uppercase + time_id + string.digits, k=12))
    ticket_id = models.CharField(max_length=100, default=generate_ticket_id)
    transaction = models.ForeignKey('Transaction', on_delete=models.CASCADE, null=True, blank=True)  # noqa
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.ticket_id if self.ticket_id else "ticket"

    class Meta:
        db_table = 'ticket'


class Transaction(models.Model):
    def generate_transaction_id():
        time_id = str(int(time.time() * 100))
        return "".join(random.choices(string.ascii_uppercase + time_id + string.digits, k=12))
    transaction_id = models.CharField(max_length=255, primary_key=True, default=generate_transaction_id)  # noqa
    external_id = models.CharField(max_length=255, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    network = models.CharField(max_length=255, null=True, blank=True)
    status_code = models.CharField(max_length=255, null=True, blank=True)
    status_message = models.CharField(max_length=255, null=True, blank=True)
    source_phone = models.CharField(max_length=255, null=True, blank=True)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, null=True, blank=True)  # noqa
    note = models.CharField(max_length=255, null=True, blank=True)
    transaction_type = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id if self.transaction_id else "transaction"


class Wallet(models.Model):
    wallet_id = models.CharField(max_length=100, default=uuid.uuid4)
    main_balance = models.DecimalField(decimal_places=2, max_digits=10, default=0.0)  # noqa
    available_balance = models.DecimalField(decimal_places=2, max_digits=50, default=0.0)  # noqa
    date_added = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def credit_available_balance(self, amount):
        self.available_balance += decimal.Decimal(amount)
        self.save()

    def debit_available_balance(self, amount):
        self.available_balance -= decimal.Decimal(amount)
        self.save()

    def credit_main_balance(self, amount):
        self.main_balance += decimal.Decimal(amount)
        self.save()

    def debit_main_balance(self, amount):
        self.main_balance -= decimal.Decimal(amount)
        self.save()

    def credit_wallet(self, amount):
        self.main_balance += decimal.Decimal(amount)
        self.available_balance += decimal.Decimal(amount)
        self.save()

    def debit_wallet(self, amount):
        self.main_balance -= decimal.Decimal(amount)
        self.available_balance -= decimal.Decimal(amount)
        self.save()

    def get_wallet_balance(self):
        return decimal.Decimal(self.main_balance)

    def __str__(self):
        return self.wallet_id

    class Meta:
        permissions = [
            ("cashout_from_wallet", "Can cashout from wallet"),
        ]

core/backend/views/booking.py
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from backend.models import Booking

from core.utils.decorators import MustLogin


class BookingListView(View):
    permission_required = [
        "backend.view_booking",
    ]
    template = "backend/lists/bookings.html"

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        if request.user.is_staff or request.user.is_superuser:
            bookings = Booking.objects.all().order_by('-id')
        elif request.user.is_agency_admin:
            bookings = Booking.objects.filter(
                trip__vehicle__agency=request.user.agency)
        context = {'bookings': bookings}
        return render(request, self.template, context)

core/backend/views/category.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.utils.html import strip_tags

from backend.models import VehicleCategory
from backend.forms import VehicleCategoryForm
from core.utils.decorators import MustLogin


class CategoryListView(PermissionRequiredMixin, View):
    permission_required = [
        "backend.view_vehiclecategory",
    ]
    template = "backend/lists/categories.html"

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        categories = VehicleCategory.objects.all().order_by('-id')
        context = {'categories': categories}
        return render(request, self.template, context)


class CreateUpdateCategory(PermissionRequiredMixin, View):
    permission_required = [
        "backend.add_vehiclecategory",
        "backend.change_vehiclecategory",
    ]
    template = "backend/create_update_category.html"

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        category_id = request.GET.get('category_id')
        category = VehicleCategory.objects.filter(id=category_id).first()
        context = {"category": category}  # noqa
        return render(request, self.template, context)

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        category_id = request.POST.get('category_id')

        if category_id:
            # category exists
            category = VehicleCategory.objects.filter(id=category_id).first()
            form = VehicleCategoryForm(request.POST, request.FILES, instance=category)  # noqa
            if form.is_valid():
                category = form.save(commit=False)
                category.save()
                messages.success(request, 'Vehicle Category Details Updated Successfully.')  # noqa
                return redirect('backend:categories')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        else:
            # it's a new category
            form = VehicleCategoryForm(request.POST, request.FILES)
            if form.is_valid():
                category = form.save(commit=False)
                category.save()
                messages.success(request, 'New Vehicle Category Created Successfully.')  # noqa
                return redirect('backend:categories')
            else:
                for field, error in form.errors.items():
                    message = f"{field.title()}: {strip_tags(error)}"
                    break
                messages.warning(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class DeleteCategory(PermissionRequiredMixin, View):
    permission_required = [
        "backend.delete_vehiclecategory",
    ]

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        return redirect('backend:categories')

    @method_decorator(MustLogin)
    def post(self, request, *args, **kwargs):
        category_id = request.POST.get('category_id')
        category = VehicleCategory.objects.filter(id=category_id).first()
        category.delete()
        messages.success(request, 'Vehicle Category Deleted Successfully.')
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

core/backend/views/ticket.py
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import PermissionRequiredMixin
from core.utils.decorators import MustLogin
from backend.models import Ticket


class TicketListView(PermissionRequiredMixin, View):
    permission_required = [
        "backend.view_ticket"
    ]

    template = "backend/lists/tickets.html"

    @method_decorator(MustLogin)
    def get(self, request, *args, **kwargs):
        if request.user.is_staff or request.user.is_superuser:
            tickets = Ticket.objects.all().order_by('-id')
        elif request.user.is_agency_admin:
            tickets = Ticket.objects.filter(
                transaction__booking__trip__vehicle__agency=request.user.agency)
        context = {'tickets': tickets}
        return render(request, self.template, context)

core/backend/templates/backend/lists/agencies.html
{% extends 'backend/base.html' %}

{% block active_item %}agencies{% endblock %}
{% block page_title %}Agencies{% endblock %}


{% block content %}
<div class="breadcrumb"style="background-color:#B9B9BA ;">
    <a href="{% url 'backend:backend' %}"><font color = "black">Dashboard</font></a>
    <a class="active"><font color = "white"><i class="bi bi-chevron-right"></font></i><font color = "black"> Agencies </font></a>
</div>


<div class="p-3">
    <h4 class="page-header"><font color = "white"><i class="bi bi-sliders me-2"></font></i> <font color = "black">Agencies</font></h4>
    <div class="row">
        <section class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title"><span>All Agencies</span></h5>
                    {% if perms.backend.add_agency %}
                    <div class="actions">
                        <a href="{% url 'backend:create_update_agency' %}"class="btn btn-dark-primary text-black"><i
                                class="bi bi-plus"></i> Add
                            Agency</a>
                    </div>
                    {% endif %}
                </div>
                <div class="card-body">
                    <table class="table table-sm data-table col-12" id="Agencies" style="min-width: 60em;">
                        <caption>List of Agencies</caption>
                        <thead>
                            <tr>
                                <th>#.</th>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Website</th>
                                <th>Approved</th>
                                <th>Date Created</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if agencies %}
                            {% for agency in agencies %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{agency.name}}</td>
                                <td>{{agency.phone}}</td>
                                <td>{{agency.email}}</td>
                                <td>{{agency.address}}</td>
                                <td>{{agency.website}}</td>
                                <td>{{agency.is_approved}}</td>
                                <td>{{agency.date_joined|date:"d M Y"}}</td>
                                <td class="text text-center d-flex">
                                    <a href="{% url 'backend:create_update_agency' %}?agency_id={{agency.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-secondary">
                                            <i class="bi bi-pencil"></i>
                                            Edit
                                        </button>
                                    </a>
                                    {% if perms.backend.delete_agency %}
                                    <a href="{% url 'backend:approve_disapprove_agency' %}?agency_id={{agency.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-secondary">
                                            <i class="bi bi-eye"></i>
                                            Details
                                        </button>
                                    </a>
                                    {% endif %}
                                    {% if perms.backend.delete_agency %}
                                    <form action="{% url 'backend:delete_agency' %}" method="POST"
                                        class="requires-confirmation"
                                        data-message="Click on okay to permanently delete this agency.">
                                        <input type="hidden" name="agency_id" value="{{agency.id}}">
                                        {% csrf_token %}
                                        <button class="btn btn-sm btn-danger">
                                            <i class="bi bi-trash"></i>
                                            Delete
                                        </button>
                                    </form>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="8" class="text-center">No Agencies Found</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

    </div>
</div>




{% endblock %}

core/backend/templates/backend/lists/categories.html
{% extends 'backend/base.html' %}

{% block active_item %}categories{% endblock %}
{% block page_title %}Categories{% endblock %}


{% block content %}
<div class="breadcrumb"style="background-color:#B9B9BA ;">
    <a href="{% url 'backend:backend' %}"> <font color ="black">Dashboard</font></a>
    <a class="active"><i class="bi bi-chevron-right"></i>  <font color ="black">Categories</font></a>
</div>

<div class="p-3">
    <h4 class="page-header"><i class="bi bi-sliders me-2"></i>  <font color ="black">Categories</font></h4>
    <div class="row">
        <section class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title"><span>All Categories</span></h5>
                    <div class="actions">
                        <a href="{% url 'backend:create_update_category' %}"
                            class="btn btn-dark-primary text-black"><i class="bi bi-plus"></i> Add
                            Category</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-sm data-table col-12" id="Categories" style="min-width: 60em;">
                        <caption>List of Categories</caption>
                        <thead>
                            <tr>
                                <th>#.</th>
                                <th>Category Name</th>
                                <th>Date Created</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if categories %}
                            {% for category in categories %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{category.name}}</td>
                                <td>{{category.date_created|date:"D d M Y"}}</td>
                                <td class="text text-center d-flex">
                                    <a href="{% url 'backend:create_update_category' %}?category_id={{category.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-primary">
                                            <i class="bi bi-pencil"></i>
                                            Edit
                                        </button>
                                    </a>

                                    <form action="{% url 'backend:delete_category' %}" method="POST"
                                        class="requires-confirmation"
                                        data-message="Click on okay to permanently delete this candidate.">
                                        <input type="hidden" name="category_id" value="{{category.id}}">
                                        {% csrf_token %}
                                        <button class="btn btn-sm btn-danger">
                                            <i class="bi bi-trash"></i>
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="4" class="text-center">No Categories Found</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

    </div>
</div>




{% endblock %}

core/backend/templates/backend/lists/vehicles.html
{% extends 'backend/base.html' %}

{% block active_item %}vehicles{% endblock %}
{% block page_title %}Vehicles{% endblock %}


{% block content %}
<div class="breadcrumb" style="background-color:#B9B9BA ;">
    <a href="{% url 'backend:backend' %}"> <font color ="black">Dashboard</font></a>
    <a class="active"> <font color ="black"><i class="bi bi-chevron-right"></font></i> <font color ="black">Vehicles</font></a>
</div>


<div class="p-3">
    <h4 class="page-header"> <font color ="white"><i class="bi bi-sliders me-2"></i></font><font color ="black"> Vehicles</font></h4>
    <div class="row">
        <section class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title"><span>All Vehicles</span></h5>
                    <div class="actions">
                        <a href="{% url 'backend:create_update_vehicle' %}" class="btn btn-dark-primary text-black"><i
                                class="bi bi-plus"></i> Add
                            Vehicle</a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-sm data-table col-12" id="Vehicles" style="min-width: 60em;">
                        <caption>List of Vehicles</caption>
                        <thead>
                            <tr>
                                <th>#.</th>
                                <th>VIN</th>
                                <th>VEHICLE NAME</th>
                                <th>CATEGORY</th>
                                <th>AGENCY</th>
                                <th>DATE ADDED</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if vehicles %}
                            {% for vehicle in vehicles %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{vehicle.vin|upper}}</td>
                                <td>{{vehicle.name}}</td>
                                <td>{{vehicle.category.name}}</td>
                                <td>{{vehicle.agency.name}}</td>
                                <td>{{vehicle.date_created|date:"d M Y"}}</td>
                                <td class="text text-center d-flex">
                                    <a href="{% url 'backend:create_update_vehicle' %}?vehicle_id={{vehicle.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-primary">
                                            <i class="bi bi-pencil"></i>
                                            Edit
                                        </button>
                                    </a>

                                    <form action="{% url 'backend:delete_vehicle' %}" method="POST"
                                        class="requires-confirmation"
                                        data-message="Click on okay to permanently delete this vehicle.">
                                        <input type="hidden" name="vehicle_id" value="{{vehicle.id}}">
                                        {% csrf_token %}
                                        <button class="btn btn-sm btn-danger">
                                            <i class="bi bi-trash"></i>
                                            Delete
                                        </button>
                                    </form>

                                    <a href="{% url 'backend:free_vehicle_seats' %}?vehicle_id={{vehicle.id}}"
                                        class="px-2">
                                        <button class="btn btn-sm btn-secondary">
                                            Free Seats
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="7" class="text-center">No Vehicles Found</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}